# Generated by Django 3.0.6 on 2020-07-14 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_price', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='store',
        ),
        migrations.AddField(
            model_name='product',
            name='product',
            field=models.CharField(default='default', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_store',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='product_price.Store'),
        ),
    ]
