# Generated by Django 3.0.5 on 2020-05-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_price', '0002_auto_20200513_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
