# Generated by Django 3.0.5 on 2020-05-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_price', '0005_auto_20200514_0156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='store',
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
