# Generated by Django 3.0.5 on 2020-05-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_price', '0007_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='product_name',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.DeleteModel(
            name='Price',
        ),
    ]
