# Generated by Django 3.0.5 on 2020-05-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_price', '0008_auto_20200515_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.CharField(default='', max_length=20),
        ),
    ]
