# Generated by Django 3.0.5 on 2020-05-15 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_price', '0010_auto_20200515_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='store',
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=2, default='', max_digits=5),
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_price.Product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='store_product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='product_price.Store'),
            preserve_default=False,
        ),
    ]
