# Generated by Django 3.0.5 on 2020-05-15 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_price', '0011_auto_20200515_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='store_product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='product_price.Store'),
        ),
    ]
