# Generated by Django 3.0.5 on 2020-05-15 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_price', '0012_auto_20200515_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='store_product',
        ),
    ]
