# Generated by Django 3.0.5 on 2020-05-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_price', '0013_remove_product_store_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Store',
        ),
        migrations.AddField(
            model_name='price',
            name='store',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
