# Generated by Django 3.0.5 on 2020-05-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_price', '0014_auto_20200515_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Price',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
