# Generated by Django 3.0.5 on 2020-05-15 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_price', '0015_auto_20200515_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('weight', models.DecimalField(decimal_places=2, default='', max_digits=5)),
                ('store_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_price.Store')),
            ],
        ),
    ]
