# Generated by Django 3.0.5 on 2020-05-15 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_price', '0017_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='store_product',
        ),
        migrations.DeleteModel(
            name='Price',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
