# Generated by Django 3.0.5 on 2020-05-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_price', '0018_auto_20200515_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default='', max_digits=5)),
                ('store', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
